apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
        - name: backend
          image: shreeganesha237/devops-backend:latest
          ports:
            - containerPort: 5000
